import { initAnonymousAuth, loadAll } from "./firebase-service.js";
import * as FS from "./firebase-service.js";
import { mountLayout } from "./layout.js";
import { $, money, num, toast, setLoading, esc, today } from "./ui.js";
const user = await initAnonymousAuth();

const content = `<section class="card"><h2>Nueva compra real</h2><p class="muted">Esta pantalla registra una compra directa y suma stock. Para calcular antes, usá Simulador.</p><form id="purchaseForm"><label>Producto</label><select id="productId" name="productId"></select><div class="formgrid form3"><div><label>Cantidad</label><input name="quantity" id="quantity" type="number" min="1" value="1" required></div><div><label>Precio compra</label><input name="unitPrice" id="unitPrice" type="number" min="0" placeholder="Automático"></div><div><label>Fecha</label><input name="date" type="date" value="${today()}"></div></div><div class="totals"><div class="total"><span>Subtotal</span><strong id="subtotal">$0</strong></div><div class="total"><span>Descuento</span><strong id="discount">$0</strong></div><div class="total"><span>Total a pagar</span><strong id="total">$0</strong></div><div class="total"><span>Ganancia estimada</span><strong id="profit">$0</strong></div></div><label>Observaciones</label><textarea name="notes"></textarea><button class="btn primary block" style="margin-top:12px">Guardar compra y sumar stock</button></form></section><section class="card"><h2>Compras recientes</h2><div class="tablewrap"><table><thead><tr><th>Fecha</th><th>Producto</th><th>Cantidad</th><th>Precio compra</th><th>Desc.</th><th>Total</th><th>Ganancia est.</th></tr></thead><tbody id="rows"></tbody></table></div></section>`;
mountLayout({active:"compras",title:"Compras",subtitle:"Registro operativo de compras reales e ingreso automático de stock.",content,uid:user.uid});
let all={};document.getElementById("refreshBtn").onclick=load;await load();
async function load(){setLoading(true,"Cargando compras...");all=await loadAll();setLoading(false);$("productId").innerHTML=all.products.filter(p=>p.active!==false).map(p=>`<option value="${p.id}">${esc(p.name)} · stock ${num(p.stock)}</option>`).join("");$("productId").onchange=()=>{const p=product();$("unitPrice").value=num(p?.purchasePrice||p?.resalePrice);preview();};$("quantity").oninput=preview;$("unitPrice").oninput=preview;$("productId").dispatchEvent(new Event("change"));drawRows();}
function product(){return all.products.find(p=>p.id===$("productId").value)}
function rate(q){if(q>=20)return .20;if(q>=15)return .15;if(q>=10)return .10;return 0}
function preview(){const p=product();const q=num($("quantity").value);const price=num($("unitPrice").value)||num(p?.purchasePrice||p?.resalePrice);const subtotal=q*price;const d=subtotal*rate(q);const total=subtotal-d;const suggested=q*num(p?.suggestedSalePrice);$("subtotal").textContent=money.format(subtotal);$("discount").textContent=`${money.format(d)} (${Math.round(rate(q)*100)}%)`;$("total").textContent=money.format(total);$("profit").textContent=money.format(suggested-total);}
function drawRows(){$("rows").innerHTML=all.purchases.map(c=>`<tr><td>${esc(c.date||"")}</td><td>${esc(c.productName)}</td><td>${num(c.quantity)}</td><td>${money.format(num(c.unitPrice))}</td><td>${Math.round(num(c.discountRate)*100)}%</td><td>${money.format(num(c.total))}</td><td>${money.format(num(c.estimatedProfit))}</td></tr>`).join("")||`<tr><td colspan="7" class="empty">Sin compras.</td></tr>`}
$("purchaseForm").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const q=Number(data.quantity);const p=product();const price=data.unitPrice===""?Number(p?.purchasePrice||p?.resalePrice):Number(data.unitPrice);if(!p)return toast("Seleccioná un producto.","bad");if(!Number.isInteger(q)||q<=0)return toast("La cantidad debe ser un entero mayor a cero.","bad");if(!Number.isFinite(price)||price<=0)return toast("Ingresá un precio de compra válido mayor a cero.","bad");if(!data.date)return toast("Seleccioná la fecha de compra.","bad");const subtotal=q*price;const d=subtotal*rate(q);const total=subtotal-d;if(!confirm(`Confirmar compra\nCantidad: ${q}\nSubtotal: ${money.format(subtotal)}\nDescuento: ${money.format(d)}\nTotal: ${money.format(total)}\n\n¿Sumar stock?`))return;setLoading(true,"Guardando compra...");try{await FS.createPurchase(data);toast("Compra guardada y stock actualizado.","ok");e.target.reset();await load()}catch(error){toast(error.message||"No se pudo guardar la compra.","bad")}finally{setLoading(false)}}
