import { initAnonymousAuth, loadAll } from "./firebase-service.js";
import * as FS from "./firebase-service.js";
import { mountLayout } from "./layout.js";
import { $, money, num, round, esc, norm, badge, toast, setLoading, openModal, closeModal, csv, today } from "./ui.js";
const user = await initAnonymousAuth();

const content = `<section class="card"><div class="actions"><button class="btn primary" id="newBtn">Nuevo paciente</button><button class="btn" id="exportBtn">Exportar CSV</button></div><div class="formgrid form2"><div><label>Buscar</label><input id="search" placeholder="Nombre, DNI o teléfono..."></div><div><label>Estado</label><select id="filter"><option value="active">Activos</option><option value="all">Todos</option><option value="inactive">Inactivos</option></select></div></div></section><section class="card"><div class="tablewrap"><table><thead><tr><th>Paciente</th><th>DNI</th><th>Teléfono</th><th>Observaciones</th><th>Estado</th><th>Acciones</th></tr></thead><tbody id="rows"></tbody></table></div></section>`;
mountLayout({active:"pacientes",title:"Pacientes",subtitle:"Alta, baja, modificación e historial.",content,uid:user.uid});
let all={patients:[],sales:[]};document.getElementById("refreshBtn").onclick=load;$("newBtn").onclick=()=>form();$("search").oninput=draw;$("filter").onchange=draw;$("exportBtn").onclick=()=>csv("pacientes.csv", rows());
await load();
async function load(){setLoading(true,"Cargando pacientes...");all=await loadAll();setLoading(false);draw();}
function rows(){let r=[...all.patients];const q=norm($("search").value);r=r.filter(p=>norm(`${p.fullName} ${p.dni} ${p.phone}`).includes(q));if($("filter").value==="active")r=r.filter(p=>p.active!==false);if($("filter").value==="inactive")r=r.filter(p=>p.active===false);return r}
function debt(id){return all.sales.filter(s=>s.patientId===id&&!s.canceled).reduce((a,s)=>a+num(s.balance),0)}
function draw(){const r=rows();$("rows").innerHTML=r.map(p=>`<tr><td><strong>${esc(p.fullName)}</strong><div class="help">${esc(p.birthDate||"")}</div></td><td>${esc(p.dni||"")}</td><td>${esc(p.phone||"")}</td><td>${esc(p.notes||"")}</td><td>${badge(p.active===false?"INACTIVO":"ACTIVO")} ${debt(p.id)>0?`<div class="help">Debe ${money.format(debt(p.id))}</div>`:""}</td><td><button class="btn" onclick="editPat('${p.id}')">Editar</button> <button class="btn" onclick="hist('${p.id}')">Historial</button> <button class="btn danger" onclick="delPat('${p.id}')">Baja</button></td></tr>`).join("")||`<tr><td colspan="6" class="empty">Sin pacientes.</td></tr>`}
window.editPat=(id)=>form(all.patients.find(p=>p.id===id));
window.delPat=async(id)=>{if(!confirm("¿Dar de baja este paciente?"))return;setLoading(true,"Dando de baja...");await FS.deactivatePatient(id);toast("Paciente inactivado","ok");await load();setLoading(false)}
window.hist=(id)=>{const p=all.patients.find(x=>x.id===id);const sales=all.sales.filter(s=>s.patientId===id);openModal("Historial de "+p.fullName,`<div class="tablewrap"><table><thead><tr><th>Fecha</th><th>Total</th><th>Pagado</th><th>Saldo</th><th>Estado</th></tr></thead><tbody>${sales.map(s=>`<tr><td>${new Date(s.date).toLocaleDateString("es-AR")}</td><td>${money.format(num(s.total))}</td><td>${money.format(num(s.paid))}</td><td>${money.format(num(s.balance))}</td><td>${badge(s.status)}</td></tr>`).join("")||`<tr><td colspan="5" class="empty">Sin historial.</td></tr>`}</tbody></table></div>`)}
function form(p={}){openModal(p.id?"Editar paciente":"Nuevo paciente",`<form id="f"><input type="hidden" name="id" value="${esc(p.id||"")}"><div class="formgrid form2"><div><label>Apellido</label><input name="lastName" required value="${esc(p.lastName||"")}"></div><div><label>Nombre</label><input name="firstName" required value="${esc(p.firstName||"")}"></div></div><div class="formgrid form3"><div><label>DNI</label><input name="dni" value="${esc(p.dni||"")}"></div><div><label>Teléfono</label><input name="phone" value="${esc(p.phone||"")}"></div><div><label>Nacimiento</label><input name="birthDate" type="date" value="${esc(p.birthDate||"")}"></div></div><label>Observaciones</label><textarea name="notes">${esc(p.notes||"")}</textarea><div class="modal-actions"><button class="btn ghost" type="button" onclick="document.getElementById('modal').close()">Cancelar</button><button class="btn primary">Guardar</button></div></form>`);document.getElementById("f").onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));setLoading(true,"Guardando paciente...");await FS.savePatient(o);toast("Paciente guardado","ok");closeModal();await load();setLoading(false)}}
