import { initAnonymousAuth, loadAll } from "./firebase-service.js";
import * as FS from "./firebase-service.js";
import { mountLayout } from "./layout.js";
import { $, money, num, round, esc, norm, badge, toast, setLoading, openModal, closeModal, csv, today } from "./ui.js";
const user = await initAnonymousAuth();

const content = `<section class="card"><h2>Deudores</h2><div class="tablewrap"><table><thead><tr><th>Paciente</th><th>Venta</th><th>Total</th><th>Pagado</th><th>Saldo</th><th>Acción</th></tr></thead><tbody id="debtors"></tbody></table></div></section><section class="card"><h2>Pagos recientes</h2><div class="tablewrap"><table><thead><tr><th>Fecha</th><th>Paciente</th><th>Método</th><th>Importe</th></tr></thead><tbody id="payments"></tbody></table></div></section>`;
mountLayout({active:"pagos",title:"Pagos y cuentas corrientes",subtitle:"Pagos parciales, saldo pendiente e historial.",content,uid:user.uid});
let all={};document.getElementById("refreshBtn").onclick=load;await load();
async function load(){setLoading(true,"Cargando pagos...");all=await loadAll();setLoading(false);const debt=all.sales.filter(s=>!s.canceled&&num(s.balance)>0);$("debtors").innerHTML=debt.map(s=>`<tr><td>${esc(s.patientName)}</td><td>${esc(s.id)}</td><td>${money.format(num(s.total))}</td><td>${money.format(num(s.paid))}</td><td>${money.format(num(s.balance))}</td><td><button class="btn primary" onclick="pay('${s.id}')">Registrar pago</button></td></tr>`).join("")||`<tr><td colspan="6" class="empty">Sin deudores.</td></tr>`;$("payments").innerHTML=all.payments.map(p=>`<tr><td>${new Date(p.date).toLocaleDateString("es-AR")}</td><td>${esc(p.patientName)}</td><td>${esc(p.method)}</td><td>${money.format(num(p.amount))}</td></tr>`).join("")||`<tr><td colspan="4" class="empty">Sin pagos.</td></tr>`}
window.pay=(id)=>{openModal("Registrar pago",`<form id="f"><input type="hidden" name="saleId" value="${id}"><div class="formgrid form2"><div><label>Importe</label><input name="amount" type="number" min="1" required></div><div><label>Método</label><select name="method"><option>EFECTIVO</option><option>TRANSFERENCIA</option><option>DEBITO</option><option>CREDITO</option></select></div></div><label>Observaciones</label><textarea name="notes"></textarea><div class="modal-actions"><button class="btn ghost" type="button" onclick="document.getElementById('modal').close()">Cancelar</button><button class="btn primary">Guardar</button></div></form>`);document.getElementById("f").onsubmit=async e=>{e.preventDefault();setLoading(true,"Guardando pago...");await FS.registerPayment(Object.fromEntries(new FormData(e.target)));toast("Pago guardado","ok");closeModal();await load();setLoading(false)}}
