import { initAnonymousAuth, loadAll } from "./firebase-service.js?v=20260627b";
import * as FS from "./firebase-service.js?v=20260627b";
import { mountLayout } from "./layout.js?v=20260627b";
import { $, money, num, esc, norm, badge, toast, setLoading, openModal, closeModal, csv } from "./ui.js";
const user = await initAnonymousAuth();

const content = `<section class="card"><div class="actions"><button class="btn primary" id="newBtn">Nuevo producto</button><button class="btn" id="importBtn">Importar Excel de precios</button><button class="btn" id="exportBtn">Exportar CSV</button><input id="excelInput" type="file" accept=".xlsx,.xls,.csv" style="display:none"></div><div class="formgrid form3"><div><label>Buscar</label><input id="search" placeholder="Nombre, código, marca..."></div><div><label>Estado</label><select id="filter"><option value="active">Activos</option><option value="all">Todos</option><option value="inactive">Inactivos</option><option value="critical">Críticos</option></select></div><div><label>Orden</label><select id="sort"><option value="name">Nombre</option><option value="stock">Menor stock</option><option value="margin">Menor margen</option></select></div></div></section><section class="card"><div class="tablewrap"><table><thead><tr><th>Producto</th><th>Marca</th><th>Categoría</th><th>Precio compra</th><th>Venta sugerida</th><th>Stock</th><th>Estado</th><th>Acciones</th></tr></thead><tbody id="rows"></tbody></table></div></section>`;
mountLayout({active:"productos",title:"Productos",subtitle:"Catálogo, importación de lista de precios, stock y edición. En pantalla siempre se muestra Precio compra.",content,uid:user.uid});
let data=[];
document.getElementById("refreshBtn").onclick=load;
$("newBtn").onclick=()=>form();
$("search").oninput=draw;
$("filter").onchange=draw;
$("sort").onchange=draw;
$("exportBtn").onclick=()=>csv("productos.csv", rows());
$("importBtn").onclick=()=>$("excelInput").click();
$("excelInput").onchange=importExcel;
await load();
async function load(){setLoading(true,"Cargando productos...");data=(await loadAll()).products;setLoading(false);draw();}
function margin(p){return num(p.suggestedSalePrice)?(num(p.suggestedSalePrice)-num(p.purchasePrice||p.resalePrice))/num(p.suggestedSalePrice):0}
function rows(){let r=[...data];const q=norm($("search").value);r=r.filter(p=>norm(`${p.name} ${p.code} ${p.brand} ${p.category}`).includes(q));const f=$("filter").value;if(f==="active")r=r.filter(p=>p.active!==false);if(f==="inactive")r=r.filter(p=>p.active===false);if(f==="critical")r=r.filter(p=>p.active!==false&&num(p.stock)<=num(p.minStock));const s=$("sort").value;if(s==="stock")r.sort((a,b)=>num(a.stock)-num(b.stock));else if(s==="margin")r.sort((a,b)=>margin(a)-margin(b));else r.sort((a,b)=>String(a.name).localeCompare(String(b.name),"es"));return r}
function draw(){const r=rows();$("rows").innerHTML=r.map(p=>`<tr><td><strong>${esc(p.name)}</strong><div class="help">${esc(p.code||"")}</div></td><td>${esc(p.brand||"")}</td><td>${esc(p.category||"")}</td><td>${money.format(num(p.purchasePrice||p.resalePrice))}</td><td>${money.format(num(p.suggestedSalePrice))}</td><td>${num(p.stock)<=num(p.minStock)?badge("BAJO STOCK"):""} ${num(p.stock)}</td><td>${badge(p.active===false?"INACTIVO":"ACTIVO")}</td><td><button class="btn" onclick="editProd('${p.id}')">Editar</button> <button class="btn danger" onclick="delProd('${p.id}')">Baja</button></td></tr>`).join("")||`<tr><td colspan="8" class="empty">Sin productos.</td></tr>`}
window.editProd=(id)=>form(data.find(p=>p.id===id));
window.delProd=async(id)=>{if(!confirm("¿Dar de baja este producto?"))return;setLoading(true,"Dando de baja...");await FS.deactivateProduct(id);toast("Producto inactivado","ok");await load();setLoading(false)}
function form(p={}){openModal(p.id?"Editar producto":"Nuevo producto",`<form id="f"><input type="hidden" name="id" value="${esc(p.id||"")}"><div class="formgrid form3"><div><label>Código</label><input name="code" value="${esc(p.code||"")}"></div><div><label>Nombre</label><input name="name" required value="${esc(p.name||"")}"></div><div><label>Marca</label><input name="brand" value="${esc(p.brand||"")}"></div></div><div class="formgrid form3"><div><label>Categoría</label><input name="category" value="${esc(p.category||"")}"></div><div><label>Stock</label><input name="stock" type="number" min="0" value="${num(p.stock)}"></div><div><label>Stock mínimo</label><input name="minStock" type="number" min="0" value="${num(p.minStock||3)}"></div></div><div class="formgrid form2"><div><label>Precio compra</label><input name="purchasePrice" type="number" min="0" value="${num(p.purchasePrice||p.resalePrice)}"></div><div><label>Venta sugerida</label><input name="suggestedSalePrice" type="number" min="0" value="${num(p.suggestedSalePrice)}"></div></div><div class="modal-actions"><button class="btn ghost" type="button" onclick="document.getElementById('modal').close()">Cancelar</button><button class="btn primary">Guardar</button></div></form>`);document.getElementById("f").onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));setLoading(true,"Guardando producto...");await FS.saveProduct(o);toast("Producto guardado","ok");closeModal();await load();setLoading(false)}}
async function importExcel(e){const file=e.target.files[0];if(!file)return;setLoading(true,"Leyendo Excel...");const dataBuffer=await file.arrayBuffer();const wb=XLSX.read(dataBuffer,{type:"array"});const sheet=wb.Sheets[wb.SheetNames[0]];const raw=XLSX.utils.sheet_to_json(sheet,{defval:""});const mapped=raw.map(r=>{const keys=Object.keys(r);const get=(names)=>{for(const n of names){const k=keys.find(x=>norm(x)===norm(n));if(k)return r[k]}return ""};return{code:get(["Código","Codigo","Cod","CODIGO"]),name:get(["Nombre","Producto","Descripcion","Descripción"]),purchasePrice:get(["Importe reventa","Reventa","Precio reventa","Precio compra"]),suggestedSalePrice:get(["Importe venta","Venta","Precio venta","Venta sugerida"]),brand:get(["Marca"]),category:get(["Categoría","Categoria"])} });const res=await FS.importProductsFromRows(mapped);setLoading(false);toast(`Importación lista: nuevos ${res.inserted||res.created||0}, actualizados ${res.updated}, omitidos ${res.skipped}`,"ok");await load();e.target.value=""}
