import { initAnonymousAuth, loadAll } from "./firebase-service.js";
import * as FS from "./firebase-service.js";
import { mountLayout } from "./layout.js";
import { $, money, num, round, esc, norm, badge, toast, setLoading, openModal, closeModal, csv, today } from "./ui.js";
const user = await initAnonymousAuth();

const content = `<section class="card"><div class="formgrid form3"><div><label>Desde</label><input id="from" type="date"></div><div><label>Hasta</label><input id="to" type="date"></div><div><label>&nbsp;</label><button class="btn block" id="exportBtn">Exportar CSV</button></div></div></section><section class="grid cols2"><article class="card"><h2>Productos más vendidos</h2><div class="tablewrap"><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Total</th><th>Ganancia</th></tr></thead><tbody id="top"></tbody></table></div></article><article class="card"><h2>Deudores</h2><div class="tablewrap"><table><thead><tr><th>Paciente</th><th>Saldo</th><th>Venta</th></tr></thead><tbody id="debt"></tbody></table></div></article></section><section class="card"><h2>Movimientos de stock</h2><div class="tablewrap"><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Producto</th><th>Cantidad</th><th>Stock resultante</th></tr></thead><tbody id="movs"></tbody></table></div></section>`;
mountLayout({active:"reportes",title:"Reportes",subtitle:"Más vendidos, rentabilidad, deudores y movimientos por período.",content,uid:user.uid});
let all={};document.getElementById("refreshBtn").onclick=load;$("from").onchange=draw;$("to").onchange=draw;$("exportBtn").onclick=()=>csv("reporte_movimientos.csv", filteredMovs());await load();
async function load(){setLoading(true,"Cargando reportes...");all=await loadAll();setLoading(false);draw();}
function inRange(date){const d=String(date||"").slice(0,10);const f=$("from").value,t=$("to").value;if(f&&d<f)return false;if(t&&d>t)return false;return true}
function filteredSales(){return all.sales.filter(s=>!s.canceled&&inRange(s.date))}
function filteredMovs(){return all.stockMovements.filter(m=>inRange(m.date))}
function draw(){const map={};filteredSales().forEach(s=>(s.items||[]).forEach(i=>{map[i.productId]??={product:i.productName,qty:0,total:0,gain:0};map[i.productId].qty+=num(i.quantity);map[i.productId].total+=num(i.quantity)*num(i.unitPrice);map[i.productId].gain+=num(i.quantity)*(num(i.unitPrice)-num(i.costPrice));}));const rows=Object.values(map).sort((a,b)=>b.qty-a.qty);$("top").innerHTML=rows.map(r=>`<tr><td>${esc(r.product)}</td><td>${r.qty}</td><td>${money.format(r.total)}</td><td>${money.format(r.gain)}</td></tr>`).join("")||`<tr><td colspan="4" class="empty">Sin datos.</td></tr>`;const debt=all.sales.filter(s=>!s.canceled&&num(s.balance)>0);$("debt").innerHTML=debt.map(s=>`<tr><td>${esc(s.patientName)}</td><td>${money.format(num(s.balance))}</td><td>${esc(s.id)}</td></tr>`).join("")||`<tr><td colspan="3" class="empty">Sin deudores.</td></tr>`;$("movs").innerHTML=filteredMovs().map(m=>`<tr><td>${new Date(m.date).toLocaleDateString("es-AR")}</td><td>${esc(m.type)}</td><td>${esc(m.productName)}</td><td>${num(m.quantity)}</td><td>${num(m.resultingStock)}</td></tr>`).join("")||`<tr><td colspan="5" class="empty">Sin movimientos.</td></tr>`}
