import { initAnonymousAuth, loadAll } from "./firebase-service.js";
import * as FS from "./firebase-service.js";
import { mountLayout } from "./layout.js";
import { $, money, num, round, esc, norm, badge, toast, setLoading, openModal, closeModal } from "./ui.js";
const user = await initAnonymousAuth();

const content = `<section class="card"><div class="actions"><button class="btn primary" id="newPatientBtn">+ Cargar nuevo paciente</button><button class="btn ghost" id="clearSaleBtn">Limpiar venta</button></div></section><section class="split"><article class="card"><h2>Nueva venta</h2><label>Buscar paciente</label><input id="patientSearch" placeholder="Nombre o DNI..."><label>Paciente</label><select id="patient"></select><label>Producto</label><select id="product"></select><div class="formgrid form3"><div><label>Cantidad</label><input id="qty" type="number" min="1" value="1"></div><div><label>Precio venta</label><input id="price" type="number" min="0"></div><div><label>&nbsp;</label><button class="btn primary block" id="addItem">Agregar</button></div></div></article><article class="card"><h2>Pagos</h2><div class="formgrid form4"><div><label>Efectivo</label><input class="pay" data-method="EFECTIVO" type="number" value="0"></div><div><label>Transferencia</label><input class="pay" data-method="TRANSFERENCIA" type="number" value="0"></div><div><label>Débito</label><input class="pay" data-method="DEBITO" type="number" value="0"></div><div><label>Crédito</label><input class="pay" data-method="CREDITO" type="number" value="0"></div></div><label>Descuento %</label><input id="discount" type="number" min="0" max="100" value="0"><label>Observaciones</label><input id="notes"><div class="totals"><div class="total"><span>Total</span><strong id="total">$0</strong></div><div class="total"><span>Pagado</span><strong id="paid">$0</strong></div><div class="total"><span>Saldo</span><strong id="balance">$0</strong></div><div class="total"><span>Estado</span><strong id="status">Pendiente</strong></div></div><button class="btn dark block" id="saveSale" style="margin-top:12px">Guardar venta</button></article></section><section class="card"><h2>Detalle</h2><div class="tablewrap"><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio</th><th>Total</th><th></th></tr></thead><tbody id="items"></tbody></table></div></section><section class="card"><h2>Ventas recientes</h2><div class="tablewrap"><table><thead><tr><th>Fecha</th><th>Paciente</th><th>Total</th><th>Pagado</th><th>Saldo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody id="sales"></tbody></table></div></section>`;
mountLayout({active:"ventas",title:"Ventas",subtitle:"Pantalla principal. Venta rápida, nuevo paciente, múltiples productos y medios de pago.",content,uid:user.uid});
let all={}, items=[];
document.getElementById("refreshBtn").onclick=load;
$("newPatientBtn").onclick=()=>patientForm();
$("clearSaleBtn").onclick=clearSale;
await load();

async function load(){setLoading(true,"Cargando ventas...");all=await loadAll();setLoading(false);drawPatients();$("product").innerHTML=all.products.filter(p=>p.active!==false).map(p=>`<option value="${p.id}">${esc(p.name)} · stock ${num(p.stock)}</option>`).join("");drawItems();drawSales();}
$("patientSearch").oninput=drawPatients;
function drawPatients(){const q=norm($("patientSearch").value);$("patient").innerHTML=all.patients.filter(p=>p.active!==false&&norm(`${p.fullName} ${p.dni}`).includes(q)).map(p=>`<option value="${p.id}">${esc(p.fullName)} ${p.dni?`· ${esc(p.dni)}`:""}</option>`).join("") || `<option value="">Sin pacientes</option>`}
function prod(){return all.products.find(p=>p.id===$("product").value)}
$("product").onchange=()=>{$("price").value=num(prod()?.suggestedSalePrice)};
$("product").dispatchEvent(new Event("change"));
$("addItem").onclick=()=>{const p=prod();const q=num($("qty").value);const price=num($("price").value)||num(p?.suggestedSalePrice);if(!p||q<=0)return toast("Producto/cantidad inválida","bad");if(num(p.stock)<q)return toast("Stock insuficiente","bad");items.push({productId:p.id,productName:p.name,quantity:q,unitPrice:price,costPrice:num(p.purchasePrice||p.resalePrice)});drawItems();}
document.querySelectorAll(".pay").forEach(i=>i.oninput=drawItems);$("discount").oninput=drawItems;
function totals(){const subtotal=items.reduce((a,i)=>a+num(i.quantity)*num(i.unitPrice),0);const discount=subtotal*(num($("discount").value)/100);const total=round(subtotal-discount);const paid=[...document.querySelectorAll(".pay")].reduce((a,i)=>a+num(i.value),0);return{subtotal,total,paid,balance:round(total-paid)}}
function drawItems(){const t=totals();$("items").innerHTML=items.map((i,k)=>`<tr><td>${esc(i.productName)}</td><td>${i.quantity}</td><td>${money.format(i.unitPrice)}</td><td>${money.format(i.quantity*i.unitPrice)}</td><td><button class="btn danger" onclick="removeItem(${k})">Quitar</button></td></tr>`).join("")||`<tr><td colspan="5" class="empty">Agregá productos.</td></tr>`;$("total").textContent=money.format(t.total);$("paid").textContent=money.format(t.paid);$("balance").textContent=money.format(Math.max(0,t.balance));$("status").textContent=t.balance<=0?"Pagada":t.paid>0?"Parcial":"Pendiente";}
window.removeItem=(k)=>{items.splice(k,1);drawItems()}
$("saveSale").onclick=async()=>{const t=totals();if(t.balance<0)return toast("El pago supera el total","bad");const payments=[...document.querySelectorAll(".pay")].map(i=>({method:i.dataset.method,amount:num(i.value)})).filter(p=>p.amount>0);setLoading(true,"Guardando venta...");await FS.createSale({patientId:$("patient").value,items,discountRate:num($("discount").value)/100,payments,notes:$("notes").value});toast("Venta guardada","ok");clearSale();await load();setLoading(false)}
function clearSale(){items=[];document.querySelectorAll(".pay").forEach(i=>i.value=0);$("discount").value=0;$("notes").value="";drawItems();}
function drawSales(){$("sales").innerHTML=all.sales.map(s=>`<tr><td>${new Date(s.date).toLocaleDateString("es-AR")}</td><td>${esc(s.patientName)}</td><td>${money.format(num(s.total))}</td><td>${money.format(num(s.paid))}</td><td>${money.format(num(s.balance))}</td><td>${badge(s.status)}</td><td>${!s.canceled?`<button class="btn danger" onclick="cancel('${s.id}')">Anular</button>`:""}</td></tr>`).join("")||`<tr><td colspan="7" class="empty">Sin ventas.</td></tr>`}
window.cancel=async(id)=>{if(!confirm("¿Anular venta y devolver stock?"))return;setLoading(true,"Anulando...");await FS.cancelSale(id);toast("Venta anulada","ok");await load();setLoading(false)}
function patientForm(){openModal("Cargar nuevo paciente",`<form id="patientForm"><div class="formgrid form2"><div><label>Apellido</label><input name="lastName" required></div><div><label>Nombre</label><input name="firstName" required></div></div><div class="formgrid form3"><div><label>DNI</label><input name="dni"></div><div><label>Teléfono</label><input name="phone"></div><div><label>Nacimiento</label><input name="birthDate" type="date"></div></div><label>Observaciones</label><textarea name="notes"></textarea><div class="modal-actions"><button class="btn ghost" type="button" onclick="document.getElementById('modal').close()">Cancelar</button><button class="btn primary">Guardar y usar</button></div></form>`);document.getElementById("patientForm").onsubmit=async e=>{e.preventDefault();setLoading(true,"Guardando paciente...");const data=Object.fromEntries(new FormData(e.target));const id=await FS.savePatient(data);toast("Paciente guardado","ok");closeModal();await load();$("patient").value=id;setLoading(false)}}
