const STORE='dervie_api_url_v1';let data={productos:[],pacientes:[],ventas:[],deudores:[],resumen:{}};let ventaItems=[];const $=id=>document.getElementById(id);const money=new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0});
document.addEventListener('DOMContentLoaded',()=>{ $('clinicName').textContent=window.DERVIE_CONFIG?.CLINIC_NAME||'Control de cremas'; bind(); $('apiUrl').value=getApi(); status(); load(); });
function bind(){document.querySelectorAll('.menu button').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>view(b.dataset.go));$('vBuscar').oninput=()=>renderProductSelect('vProducto',$('vBuscar').value);$('cBuscar').oninput=()=>renderProductSelect('cProducto',$('cBuscar').value);$('vProducto').onchange=setVentaPrecio;$('cProducto').onchange=()=>{setCompraPrecio();previewCompra()};$('cCant').oninput=previewCompra;$('cPrecio').oninput=previewCompra;$('vDesc').oninput=renderVenta;$('vPago').oninput=renderVenta;$('pBuscar').oninput=renderPacientes;$('addVenta').onclick=addVenta;$('saveVenta').onclick=saveVenta;$('saveCompra').onclick=saveCompra;$('savePaciente').onclick=savePaciente;$('importCatalogo').onclick=importCatalogo;$('reload').onclick=load;$('saveApi').onclick=saveApi;$('testApi').onclick=()=>{saveApi();load()};$('confirmPay').onclick=confirmPay;}
function view(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('.menu button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));}
function getApi(){return localStorage.getItem(STORE)||window.DERVIE_CONFIG?.API_URL||''}function connected(){return getApi().startsWith('http')&&getApi().includes('/exec')}function status(){const el=$('status');el.textContent=connected()?'Conectado':'Sin conectar';el.className='status '+(connected()?'ok':'warn')}
async function api(action,payload={}){if(!connected())throw new Error('Falta configurar URL de Apps Script');const r=await fetch(getApi(),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Error Apps Script');return j.data}
async function load(){status();if(!connected()){renderAll();return}try{data=await api('getDatosIniciales');renderAll();toast('Datos cargados','ok')}catch(e){toast(e.message,'bad')}}
function renderAll(){renderPatientSelect();renderProductSelect('vProducto',$('vBuscar').value);renderProductSelect('cProducto',$('cBuscar').value);setVentaPrecio();setCompraPrecio();previewCompra();renderVenta();renderStock();renderPacientes();renderDeudores();renderResumen()}
function renderPatientSelect(){const ps=data.pacientes||[];$('vPaciente').innerHTML=ps.length?ps.map(p=>`<option value="${esc(p.ID_PACIENTE)}">${esc(p.PACIENTE)}</option>`).join(''):'<option value="">Cargá paciente</option>'}
function renderProductSelect(id,q=''){const rows=(data.productos||[]).filter(p=>norm(`${p.CODIGO} ${p.PRODUCTO} ${p.DESCRIPCION}`).includes(norm(q)));$(id).innerHTML=rows.length?rows.map(p=>`<option value="${esc(p.ID_PRODUCTO)}">${esc(p.CODIGO)} | ${esc(p.PRODUCTO)} | stock ${num(p.STOCK_ACTUAL)}</option>`).join(''):'<option value="">Sin productos</option>'}
function product(id){return(data.productos||[]).find(p=>p.ID_PRODUCTO===id)}function setVentaPrecio(){const p=product($('vProducto').value);$('vPrecio').placeholder=p?num(p.PRECIO_VENTA_SUGERIDO):'Automático'}function setCompraPrecio(){const p=product($('cProducto').value);$('cPrecio').placeholder=p?num(p.PRECIO_COMPRA_REVENTA):'Automático'}
function addVenta(){const p=product($('vProducto').value);if(!p)return toast('Seleccioná producto','bad');const c=num($('vCant').value);if(c<=0)return toast('Cantidad inválida','bad');if(num(p.STOCK_ACTUAL)<c)return toast(`Stock insuficiente. Disponible: ${num(p.STOCK_ACTUAL)}`,'bad');const pm=num($('vPrecio').value);ventaItems.push({idProducto:p.ID_PRODUCTO,codigo:p.CODIGO,producto:p.PRODUCTO,cantidad:c,precioUnitario:pm>0?pm:num(p.PRECIO_VENTA_SUGERIDO)});$('vCant').value=1;$('vPrecio').value='';renderVenta()}
function renderVenta(){const tb=$('vDetalle');tb.innerHTML=ventaItems.length?ventaItems.map((it,i)=>`<tr><td><b>${esc(it.producto)}</b><br><span class="muted">Código ${esc(it.codigo)}</span></td><td>${it.cantidad}</td><td>${money.format(it.precioUnitario)}</td><td>${money.format(it.precioUnitario*it.cantidad)}</td><td><button class="light" onclick="removeVenta(${i})">Quitar</button></td></tr>`).join(''):'<tr><td colspan="5">Agregá productos.</td></tr>';const sub=ventaItems.reduce((a,it)=>a+it.precioUnitario*it.cantidad,0),d=pct($('vDesc').value),dm=sub*d,total=sub-dm,pago=Math.min(num($('vPago').value),total);$('vSub').textContent=money.format(sub);$('vDescMonto').textContent=money.format(dm);$('vTotal').textContent=money.format(total);$('vSaldo').textContent=money.format(Math.max(0,total-pago))}function removeVenta(i){ventaItems.splice(i,1);renderVenta()}
async function saveVenta(){if(!ventaItems.length)return toast('Agregá productos','bad');if(!$('vPaciente').value)return toast('Seleccioná paciente','bad');try{await api('registrarVenta',{idPaciente:$('vPaciente').value,items:ventaItems,descuentoGeneral:pct($('vDesc').value),pagado:num($('vPago').value),formaPago:$('vForma').value,observaciones:$('vObs').value});ventaItems=[];$('vDesc').value=0;$('vPago').value=0;$('vObs').value='';await load();toast('Venta guardada','ok')}catch(e){toast(e.message,'bad')}}
function discCompra(p,c){if(num(p.CANT_DESC_2)>0&&c>=num(p.CANT_DESC_2))return num(p.DESC_2);if(num(p.CANT_DESC_1)>0&&c>=num(p.CANT_DESC_1))return num(p.DESC_1);return 0}function previewCompra(){const p=product($('cProducto').value);if(!p)return;const c=num($('cCant').value),pr=num($('cPrecio').value)||num(p.PRECIO_COMPRA_REVENTA),d=discCompra(p,c),t=c*pr*(1-d);$('cTotal').value=`${money.format(t)} (${Math.round(d*100)}% desc.)`}
async function saveCompra(){const p=product($('cProducto').value);if(!p)return toast('Seleccioná producto','bad');const c=num($('cCant').value);if(c<=0)return toast('Cantidad inválida','bad');try{await api('registrarCompra',{idProducto:p.ID_PRODUCTO,cantidad:c,precioCompra:num($('cPrecio').value)||num(p.PRECIO_COMPRA_REVENTA),observaciones:$('cObs').value});$('cCant').value=1;$('cPrecio').value='';$('cObs').value='';await load();toast('Compra registrada','ok')}catch(e){toast(e.message,'bad')}}
async function savePaciente(){const p=$('pNombre').value.trim();if(!p)return toast('Cargá paciente','bad');try{await api('crearPaciente',{paciente:p,telefono:$('pTel').value,observaciones:$('pObs').value});$('pNombre').value='';$('pTel').value='';$('pObs').value='';await load();toast('Paciente guardado','ok')}catch(e){toast(e.message,'bad')}}
async function importCatalogo(){if(!confirm('Importar catálogo a Productos? No borra stock existente.'))return;try{await api('importarCatalogo');await load();toast('Catálogo importado','ok')}catch(e){toast(e.message,'bad')}}
function renderStock(){const rows=data.productos||[];$('stockRows').innerHTML=rows.length?rows.map(p=>`<tr><td>${esc(p.CODIGO)}</td><td><b>${esc(p.PRODUCTO)}</b><br><span class="muted">${esc(p.DESCRIPCION||'')}</span></td><td>${money.format(num(p.PRECIO_COMPRA_REVENTA))}</td><td>${money.format(num(p.PRECIO_VENTA_SUGERIDO))}</td><td>${num(p.STOCK_ACTUAL)}</td></tr>`).join(''):'<tr><td colspan="5">Sin productos. Usá Importar catálogo.</td></tr>'}
function renderPacientes(){const q=norm($('pBuscar').value),rows=(data.pacientes||[]).filter(p=>norm(`${p.PACIENTE} ${p.TELEFONO} ${p.OBSERVACIONES}`).includes(q));$('pacRows').innerHTML=rows.length?rows.map(p=>`<tr><td><b>${esc(p.PACIENTE)}</b></td><td>${esc(p.TELEFONO||'')}</td><td>${esc(p.OBSERVACIONES||'')}</td></tr>`).join(''):'<tr><td colspan="3">Sin pacientes.</td></tr>'}
function renderDeudores(){const rows=data.deudores||[];$('deudRows').innerHTML=rows.length?rows.map(v=>`<tr><td>${date(v.FECHA)}</td><td><b>${esc(v.PACIENTE)}</b></td><td>${money.format(num(v.TOTAL_FINAL))}</td><td>${money.format(num(v.TOTAL_PAGADO))}</td><td><b>${money.format(num(v.SALDO))}</b></td><td>${badge(v.ESTADO)}</td><td><button class="primary" onclick="openPay('${esc(v.ID_VENTA)}')">Pago</button></td></tr>`).join(''):'<tr><td colspan="7">Sin deudores.</td></tr>'}
function renderResumen(){const r=data.resumen||{};$('kVentas').textContent=money.format(num(r.ventas));$('kCobrado').textContent=money.format(num(r.cobrado));$('kDeuda').textContent=money.format(num(r.deuda));$('kStock').textContent=money.format(num(r.stockValorizado))}
function openPay(id){const v=(data.ventas||[]).find(x=>x.ID_VENTA===id);if(!v)return;$('payVenta').value=id;$('payImporte').value=num(v.SALDO);$('payInfo').textContent=`${v.PACIENTE} · saldo ${money.format(num(v.SALDO))}`;$('payDialog').showModal()}async function confirmPay(e){e.preventDefault();try{await api('registrarPago',{idVenta:$('payVenta').value,importe:num($('payImporte').value),formaPago:$('payForma').value,observaciones:$('payObs').value});$('payDialog').close();await load();toast('Pago registrado','ok')}catch(err){toast(err.message,'bad')}}
function saveApi(){const u=$('apiUrl').value.trim();if(!u.includes('/exec'))return toast('Pegá URL /exec','bad');localStorage.setItem(STORE,u);status();toast('Conexión guardada','ok')}function badge(e){if(e==='Pagada')return'<span class="badge ok">Pagada</span>';if(e==='Anulada')return'<span class="badge bad">Anulada</span>';return`<span class="badge warn">${esc(e||'Pendiente')}</span>`}function pct(v){let n=num(v);if(n>1)n/=100;return Math.max(0,Math.min(1,n))}function num(v){if(v==null||v==='')return 0;const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:0}function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}function date(v){const d=new Date(v);return Number.isNaN(d.getTime())?String(v||''):d.toLocaleDateString('es-AR')}function toast(m,t=''){const el=$('toast');el.textContent=m;el.className=`toast show ${t}`;setTimeout(()=>el.className='toast',3200)}window.removeVenta=removeVenta;window.openPay=openPay;
