const SPREADSHEET_ID = '18K0DbRbM9ztIzfTmUIAzAUltrsff96dfjaCcNiLCnVE';
const SHEETS={CONFIG:'Configuracion',CATALOGO:'CatalogoDervie',PRODUCTOS:'Productos',PACIENTES:'Pacientes',COMPRAS:'Compras',VENTAS:'Ventas',DETALLE:'DetalleVentas',PAGOS:'Pagos',MOV:'MovimientosStock'};
const HEADERS={
Configuracion:['Campo','Valor'],
CatalogoDervie:['ID_PRODUCTO','CODIGO','PRODUCTO','DESCRIPCION','CATEGORIA','PRECIO_COMPRA_REVENTA','PRECIO_VENTA_SUGERIDO','PRECIO_VENTA_PROPIO','STOCK_ACTUAL','ACTIVO','CANT_DESC_1','DESC_1','CANT_DESC_2','DESC_2','FECHA_ACTUALIZACION'],
Productos:['ID_PRODUCTO','CODIGO','PRODUCTO','DESCRIPCION','CATEGORIA','PRECIO_COMPRA_REVENTA','PRECIO_VENTA_SUGERIDO','PRECIO_VENTA_PROPIO','STOCK_ACTUAL','ACTIVO','CANT_DESC_1','DESC_1','CANT_DESC_2','DESC_2','FECHA_ACTUALIZACION'],
Pacientes:['ID_PACIENTE','FECHA_ALTA','PACIENTE','TELEFONO','OBSERVACIONES','ACTIVO'],
Compras:['ID_COMPRA','FECHA','ID_PRODUCTO','PRODUCTO','CANTIDAD','PRECIO_COMPRA_UNIT','DESCUENTO_APLICADO','TOTAL_BRUTO','TOTAL_FINAL','OBSERVACIONES'],
Ventas:['ID_VENTA','FECHA','ID_PACIENTE','PACIENTE','TOTAL_BRUTO','DESCUENTO_TOTAL','TOTAL_FINAL','TOTAL_PAGADO','SALDO','ESTADO','FORMA_PAGO','OBSERVACIONES'],
DetalleVentas:['ID_VENTA','ID_PRODUCTO','PRODUCTO','CANTIDAD','PRECIO_UNITARIO','DESCUENTO_GENERAL','TOTAL_LINEA'],
Pagos:['ID_PAGO','ID_VENTA','FECHA','PACIENTE','IMPORTE','FORMA_PAGO','OBSERVACIONES'],
MovimientosStock:['ID_MOVIMIENTO','FECHA','TIPO','ID_REFERENCIA','ID_PRODUCTO','PRODUCTO','CANTIDAD','STOCK_RESULTANTE','OBSERVACIONES']};
function doGet(){return json_({ok:true,data:{message:'Backend Dervie activo'}})}
function doPost(e){try{const b=JSON.parse(e.postData&&e.postData.contents?e.postData.contents:'{}');let d;switch(b.action){case'getDatosIniciales':d=getDatosIniciales();break;case'inicializarBase':d=inicializarBase();break;case'importarCatalogo':d=importarCatalogo();break;case'crearPaciente':d=crearPaciente(b.payload||{});break;case'registrarCompra':d=registrarCompra(b.payload||{});break;case'registrarVenta':d=registrarVenta(b.payload||{});break;case'registrarPago':d=registrarPago(b.payload||{});break;default:throw new Error('Acción no reconocida: '+b.action)}return json_({ok:true,data:d})}catch(err){return json_({ok:false,error:err.message||String(err)})}}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}function ss_(){return SpreadsheetApp.openById(SPREADSHEET_ID)}
function inicializarBase(){Object.keys(HEADERS).forEach(n=>{let sh=ss_().getSheetByName(n);if(!sh)sh=ss_().insertSheet(n);ensure_(sh,HEADERS[n])});const c=sheet_(SHEETS.CONFIG);if(c.getLastRow()<=1)c.getRange(1,1,7,2).setValues([['Campo','Valor'],['NombreSistema','Control de Cremas'],['TextoPersona','Paciente'],['PermitirStockNegativo','NO'],['ReglaDescuentoCompra1','10 unidades = 10%'],['ReglaDescuentoCompra2','15 unidades = 20%'],['FechaInstalacion',new Date()]]);migrarCatalogo_();return getDatosIniciales()}
function getDatosIniciales(){inicializarBaseLite_();const productos=objects_(SHEETS.PRODUCTOS).map(prod_).filter(p=>String(p.ACTIVO||'SI').toUpperCase()!=='NO');const pacientes=objects_(SHEETS.PACIENTES).filter(p=>String(p.ACTIVO||'SI').toUpperCase()!=='NO');const ventas=objects_(SHEETS.VENTAS).map(v=>({ID_VENTA:clean_(v.ID_VENTA),FECHA:v.FECHA,ID_PACIENTE:clean_(v.ID_PACIENTE),PACIENTE:clean_(v.PACIENTE),TOTAL_BRUTO:num_(v.TOTAL_BRUTO),DESCUENTO_TOTAL:num_(v.DESCUENTO_TOTAL),TOTAL_FINAL:num_(v.TOTAL_FINAL),TOTAL_PAGADO:num_(v.TOTAL_PAGADO),SALDO:num_(v.SALDO),ESTADO:clean_(v.ESTADO)||'Pendiente',FORMA_PAGO:clean_(v.FORMA_PAGO),OBSERVACIONES:clean_(v.OBSERVACIONES)}));const deudores=ventas.filter(v=>v.SALDO>0&&v.ESTADO!=='Anulada');return{productos,pacientes,ventas,deudores,resumen:{ventas:sum_(ventas.filter(v=>v.ESTADO!=='Anulada'),'TOTAL_FINAL'),cobrado:sum_(ventas.filter(v=>v.ESTADO!=='Anulada'),'TOTAL_PAGADO'),deuda:sum_(deudores,'SALDO'),stockValorizado:productos.reduce((a,p)=>a+num_(p.STOCK_ACTUAL)*num_(p.PRECIO_COMPRA_REVENTA),0)}}}
function inicializarBaseLite_(){Object.keys(HEADERS).forEach(n=>{if(!ss_().getSheetByName(n)){let sh=ss_().insertSheet(n);ensure_(sh,HEADERS[n])}})}
function importarCatalogo(){const lock=LockService.getScriptLock();lock.waitLock(10000);try{inicializarBase();const cat=objects_(SHEETS.CATALOGO).map(prod_).filter(p=>String(p.ACTIVO||'SI').toUpperCase()!=='NO'&&p.PRECIO_COMPRA_REVENTA>0&&p.PRECIO_VENTA_SUGERIDO>0);const existentes=objects_(SHEETS.PRODUCTOS);const ids={};existentes.forEach(p=>ids[clean_(p.ID_PRODUCTO)]=true);let ins=0;cat.forEach(p=>{if(!ids[p.ID_PRODUCTO]){append_(SHEETS.PRODUCTOS,Object.assign({},p,{STOCK_ACTUAL:0}));ins++}});return{insertados:ins,totalCatalogo:cat.length}}finally{lock.releaseLock()}}
function crearPaciente(d){const pac=clean_(d.paciente);if(!pac)throw new Error('Cargá paciente');const obj={ID_PACIENTE:id_('PAC'),FECHA_ALTA:new Date(),PACIENTE:pac,TELEFONO:clean_(d.telefono),OBSERVACIONES:clean_(d.observaciones),ACTIVO:'SI'};append_(SHEETS.PACIENTES,obj);return obj}
function registrarCompra(d){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const id=clean_(d.idProducto),cant=num_(d.cantidad);if(!id||cant<=0)throw new Error('Producto o cantidad inválida');const p=getProducto_(id);if(!p)throw new Error('No encontré producto');const precio=num_(d.precioCompra)||p.PRECIO_COMPRA_REVENTA,desc=descCompra_(p,cant),bruto=cant*precio,final=round_(bruto*(1-desc)),idc=id_('COM');append_(SHEETS.COMPRAS,{ID_COMPRA:idc,FECHA:new Date(),ID_PRODUCTO:id,PRODUCTO:p.PRODUCTO,CANTIDAD:cant,PRECIO_COMPRA_UNIT:precio,DESCUENTO_APLICADO:desc,TOTAL_BRUTO:bruto,TOTAL_FINAL:final,OBSERVACIONES:clean_(d.observaciones)});const stock=stock_(id,cant);append_(SHEETS.MOV,{ID_MOVIMIENTO:id_('MOV'),FECHA:new Date(),TIPO:'COMPRA',ID_REFERENCIA:idc,ID_PRODUCTO:id,PRODUCTO:p.PRODUCTO,CANTIDAD:cant,STOCK_RESULTANTE:stock,OBSERVACIONES:clean_(d.observaciones)});return{idCompra:idc,stock,totalFinal:final}}finally{lock.releaseLock()}}
function registrarVenta(d){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const idPac=clean_(d.idPaciente),items=d.items||[];if(!idPac)throw new Error('Seleccioná paciente');if(!items.length)throw new Error('Agregá productos');const pac=objects_(SHEETS.PACIENTES).find(p=>clean_(p.ID_PACIENTE)===idPac);if(!pac)throw new Error('No encontré paciente');const idv=id_('VTA'),desc=pct_(d.descuentoGeneral);let bruto=0,final=0;items.forEach(it=>{const p=getProducto_(it.idProducto),cant=num_(it.cantidad);if(!p)throw new Error('Producto inválido');if(cant<=0)throw new Error('Cantidad inválida');if(num_(p.STOCK_ACTUAL)<cant)throw new Error('Stock insuficiente de '+p.PRODUCTO+'. Disponible: '+p.STOCK_ACTUAL);const precio=num_(it.precioUnitario)||p.PRECIO_VENTA_SUGERIDO,lineaBruta=cant*precio,linea=round_(lineaBruta*(1-desc));bruto+=lineaBruta;final+=linea;append_(SHEETS.DETALLE,{ID_VENTA:idv,ID_PRODUCTO:p.ID_PRODUCTO,PRODUCTO:p.PRODUCTO,CANTIDAD:cant,PRECIO_UNITARIO:precio,DESCUENTO_GENERAL:desc,TOTAL_LINEA:linea});const st=stock_(p.ID_PRODUCTO,-cant);append_(SHEETS.MOV,{ID_MOVIMIENTO:id_('MOV'),FECHA:new Date(),TIPO:'VENTA',ID_REFERENCIA:idv,ID_PRODUCTO:p.ID_PRODUCTO,PRODUCTO:p.PRODUCTO,CANTIDAD:-cant,STOCK_RESULTANTE:st,OBSERVACIONES:'Venta a paciente'})});bruto=round_(bruto);final=round_(final);const pagado=Math.min(num_(d.pagado),final),saldo=round_(final-pagado),estado=saldo<=0?'Pagada':(pagado>0?'Parcial':'Pendiente');append_(SHEETS.VENTAS,{ID_VENTA:idv,FECHA:new Date(),ID_PACIENTE:idPac,PACIENTE:pac.PACIENTE,TOTAL_BRUTO:bruto,DESCUENTO_TOTAL:round_(bruto-final),TOTAL_FINAL:final,TOTAL_PAGADO:pagado,SALDO:saldo,ESTADO:estado,FORMA_PAGO:clean_(d.formaPago),OBSERVACIONES:clean_(d.observaciones)});if(pagado>0)append_(SHEETS.PAGOS,{ID_PAGO:id_('PAG'),ID_VENTA:idv,FECHA:new Date(),PACIENTE:pac.PACIENTE,IMPORTE:pagado,FORMA_PAGO:clean_(d.formaPago),OBSERVACIONES:'Pago al crear venta'});return{idVenta:idv,totalFinal:final,saldo,estado}}finally{lock.releaseLock()}}
function registrarPago(d){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const id=clean_(d.idVenta),imp=num_(d.importe);if(!id||imp<=0)throw new Error('Pago inválido');const sh=sheet_(SHEETS.VENTAS),vals=sh.getDataRange().getValues(),idx=index_(vals[0].map(clean_)),r=find_(vals,idx.ID_VENTA,id);if(r<0)throw new Error('No encontré venta');const total=num_(vals[r][idx.TOTAL_FINAL]),nuevo=Math.min(total,num_(vals[r][idx.TOTAL_PAGADO])+imp),saldo=round_(total-nuevo),estado=saldo<=0?'Pagada':'Parcial';sh.getRange(r+1,idx.TOTAL_PAGADO+1).setValue(nuevo);sh.getRange(r+1,idx.SALDO+1).setValue(saldo);sh.getRange(r+1,idx.ESTADO+1).setValue(estado);append_(SHEETS.PAGOS,{ID_PAGO:id_('PAG'),ID_VENTA:id,FECHA:new Date(),PACIENTE:vals[r][idx.PACIENTE],IMPORTE:imp,FORMA_PAGO:clean_(d.formaPago),OBSERVACIONES:clean_(d.observaciones)});return{idVenta:id,nuevoPagado:nuevo,saldo,estado}}finally{lock.releaseLock()}}
function migrarCatalogo_(){const cat=sheet_(SHEETS.CATALOGO);if(cat.getLastRow()>1)return;let src=null,hr=-1;ss_().getSheets().forEach(sh=>{const v=sh.getDataRange().getValues();for(let r=0;r<v.length;r++){if(v[r].map(clean_).includes('ID_PRODUCTO')){src=sh;hr=r;return}}});if(!src)return;const vals=src.getDataRange().getValues(),h=vals[hr].map(clean_),idc=h.indexOf('ID_PRODUCTO');vals.slice(hr+1).filter(r=>clean_(r[idc])).forEach(r=>{let o={};h.forEach((k,i)=>o[k]=r[i]);append_(SHEETS.CATALOGO,o)})}
function getProducto_(id){return objects_(SHEETS.PRODUCTOS).map(prod_).find(p=>p.ID_PRODUCTO===clean_(id))}function prod_(p){return{ID_PRODUCTO:clean_(p.ID_PRODUCTO),CODIGO:clean_(p.CODIGO),PRODUCTO:clean_(p.PRODUCTO),DESCRIPCION:clean_(p.DESCRIPCION),CATEGORIA:clean_(p.CATEGORIA),PRECIO_COMPRA_REVENTA:num_(p.PRECIO_COMPRA_REVENTA),PRECIO_VENTA_SUGERIDO:num_(p.PRECIO_VENTA_SUGERIDO),PRECIO_VENTA_PROPIO:num_(p.PRECIO_VENTA_PROPIO),STOCK_ACTUAL:num_(p.STOCK_ACTUAL),ACTIVO:clean_(p.ACTIVO)||'SI',CANT_DESC_1:num_(p.CANT_DESC_1)||10,DESC_1:pct_(p.DESC_1)||.10,CANT_DESC_2:num_(p.CANT_DESC_2)||15,DESC_2:pct_(p.DESC_2)||.20,FECHA_ACTUALIZACION:p.FECHA_ACTUALIZACION||new Date()}}
function descCompra_(p,c){if(num_(p.CANT_DESC_2)>0&&c>=num_(p.CANT_DESC_2))return pct_(p.DESC_2);if(num_(p.CANT_DESC_1)>0&&c>=num_(p.CANT_DESC_1))return pct_(p.DESC_1);return 0}function stock_(id,delta){const sh=sheet_(SHEETS.PRODUCTOS),vals=sh.getDataRange().getValues(),idx=index_(vals[0].map(clean_)),r=find_(vals,idx.ID_PRODUCTO,id);if(r<0)throw new Error('No encontré producto para stock');const nuevo=num_(vals[r][idx.STOCK_ACTUAL])+num_(delta);if(nuevo<0)throw new Error('La operación dejaría stock negativo');sh.getRange(r+1,idx.STOCK_ACTUAL+1).setValue(nuevo);if(idx.FECHA_ACTUALIZACION!==undefined)sh.getRange(r+1,idx.FECHA_ACTUALIZACION+1).setValue(new Date());return nuevo}
function sheet_(n){const sh=ss_().getSheetByName(n);if(!sh)throw new Error('Falta hoja '+n);return sh}function objects_(n){const sh=sheet_(n),vals=sh.getDataRange().getValues();if(vals.length<=1)return[];const h=vals[0].map(clean_);return vals.slice(1).filter(r=>r.some(c=>c!==''&&c!==null)).map(r=>{let o={};h.forEach((k,i)=>o[k]=r[i]);return o})}function append_(n,o){const sh=sheet_(n);ensure_(sh,HEADERS[n]||Object.keys(o));const h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(clean_);sh.appendRow(h.map(k=>o[k]!==undefined?o[k]:''))}function ensure_(sh,h){if(sh.getLastRow()===0||sh.getRange(1,1).getValue()==='')sh.getRange(1,1,1,h.length).setValues([h]);else{const cur=sh.getRange(1,1,1,Math.max(sh.getLastColumn(),1)).getValues()[0].map(clean_);h.forEach(x=>{if(!cur.includes(x))sh.getRange(1,sh.getLastColumn()+1).setValue(x)})}sh.setFrozenRows(1);sh.getRange(1,1,1,sh.getLastColumn()).setFontWeight('bold').setBackground('#e8ded6').setFontColor('#2d2520')}
function index_(h){let o={};h.forEach((x,i)=>o[x]=i);return o}function find_(vals,col,v){for(let i=1;i<vals.length;i++)if(clean_(vals[i][col])===clean_(v))return i;return-1}function id_(p){return p+'-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMddHHmmss')+'-'+Math.floor(Math.random()*1000)}function clean_(v){return String(v===undefined||v===null?'':v).trim()}function num_(v){if(v===undefined||v===null||v==='')return 0;const n=Number(String(v).replace(',','.'));return isNaN(n)?0:n}function pct_(v){let n=num_(v);if(n>1)n/=100;return Math.max(0,Math.min(1,n))}function sum_(rows,f){return rows.reduce((a,r)=>a+num_(r[f]),0)}function round_(n){return Math.round((num_(n)+Number.EPSILON)*100)/100}
